# Generated by Django 4.1.7 on 2023-04-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_app', '0002_alter_manufacturer_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
