# Generated by Django 4.1.7 on 2023-05-07 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_app', '0003_alter_manufacturer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='responsible_purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturers', to=settings.AUTH_USER_MODEL),
        ),
    ]
